name: Frontend Deployment
run-name: ${{ github.actor }} is testing, building and deploying the frontend.
on: 
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd ui
          npm i

      - name: Build
        run: |
          cd ui
          echo PUBLIC_API_BASE_URL=${{ vars.PUBLIC_API_BASE_URL }} > .env
          echo PUBLIC_OSRM_URL=${{ vars.PUBLIC_OSRM_URL }} >> .env
          echo PUBLIC_FRONTEND_PASSWORD_SALT=${{ vars.PUBLIC_FRONTEND_PASSWORD_SALT }} >> .env
          npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_THRAIN }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 hoenson.xyz >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          cd ui
          rsync -avz --delete dist/ thrain@hoenson.xyz:/home/krushr/frontend
